name: ansible playbook linting
on:
  pull_request: 
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AnsibleLint:
    runs-on: ubuntu-latest

    steps:
    - name: Check code out from github
      uses: actions/checkout@v3
    - name: lint ansible playbook playbook.yml
      uses: ansible/ansible-lint@main
